### ISSUE TITLE
Add support for TypeScrupt 1.5

### ISSUE THREAD

**Issue by niemyjski** [sergeyt/karma-typescript-preprocessor#30]
TypeScript 1.5 adds support for es6 and uses a new tsconfig.json that defines all of the ts dependencies.. Please note that we still need to be able to define external files to load (non typescript files)

**Comment by niemyjski** [comment]
@sergeyt do you have any recommendations for me. I've been unable to get this plugin working with my project and have tried many things: https://github.com/exceptionless/Exceptionless.JavaScript

I always get errors and it fails everytime.

**Comment by dotDeeka** [comment]
+1

**Comment by sergeyt** [comment]
@niemyjski I think you should try to get running test only for one spec file, lets say it will be Utils-spec.ts. Since this file (and most of your code) uses modules you should try to use [karma-requirejs](https://github.com/karma-runner/karma-requirejs). Please see #22 to find example how to configure karma-requirejs plugin.

re tsconfig.json - I guess this requires to rewrite the preprocessor to [tsproject](https://github.com/ToddThomson/tsproject) module to compile TypeScript files.

Other idea is to prepare JS file for karma runner without use of the preprocessor, i.e. try to create `tsconfig.test.json` file where you specify all files including jasmine spec files. Compile typescript files with grunt into temp test folder, configure karma to run these JS files.

**Comment by niemyjski** [comment]
Thanks! I ended up transpiling everything.

**Comment by johnjelinek** [comment]
@niemyjski: how are you doing the transpiling? karma + systemjs/jspm + traceur/babel pointing to src/**/*.ts & test/**/*.ts?

**Comment by niemyjski** [comment]
I ended up using [tsproject](https://github.com/toddthomson/tsproject) (great project) and doing [this](https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/gulpfile.js#L87-L114)

**Comment by claycephas** [comment]
+1

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support latest compiler with all compiler options. Please retry again.
